### ISSUE TITLE
495にチーズピザ１つ

### ISSUE THREAD

**Issue by uehara1414** [nicofun/open-source-pizza#9]
あたたかいのたべたいやきとりもたべたい、ひとこない失敗した失敗した失敗した失敗した失敗した失敗した失敗した失敗した失敗した失敗した失敗した失敗した失敗した失敗した失敗した失敗した失敗した失敗した失敗した失敗した失敗した失敗した失敗した失敗した失敗した失敗した失敗した失敗した失敗した失敗した失敗した失敗した失敗した失敗した失敗した失敗した失敗した失敗した失敗した失敗した失敗した失敗した失敗した失敗した失敗した失敗した失敗した失敗した失敗した失敗した失敗した失敗した失敗した失敗した

**Comment by uehara1414** [comment]
↑ 書いたのは rei です

**Comment by defaultcf** [comment]
今年度の営業は終了しました。また次年度のご利用をお待ちしております。
